### ISSUE TITLE
Remove commercial support text

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi.dev#367]
We should remove references to commercial support, since that will be traveling with Eran and no longer officially supported by hapi itself given https://github.com/hapijs/hapi/issues/4113.  Eran has offered to go over any of these website changes together.

**Comment by devinivy** [comment]
@Nargonath I intend to lend a hand with this, but if you find time to get started without me please don't hesitate! 👍

**Comment by Nargonath** [comment]
@devinivy Alright. I'll mention it here if I start  working on it. 👍

**Comment by Nargonath** [comment]
Perhaps I was thinking also that we could do a first pass and delete what we find then include Eran to double check with him. What do you think?

**Comment by Marsup** [comment]
Shouldn't it still be around as long as Eran is providing support? That would be very weird to find it elsewhere.

**Comment by Nargonath** [comment]
@Marsup Eran asked us to remove any mentions of the commercial licenses on the website as we took over since it has nothing to do with us.

**Comment by hueniverse** [comment]
I've already removed the commercial support text. What is left are linked to the api docs of the commercial branches as well as the listing of the commercial versions available. We should leave those for now especially since there are a lot of people who still use open source v16-18 that rely on these docs even if their version is deprecated.
