### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by damusix** [hapijs/hapi.dev#370]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  n/a
* *module version*: n/a
* *environment* (e.g. node, browser, native): n/a
* *used with* (e.g. hapi application, another framework, standalone, ...): n/a
* *any other relevant information*: n/a

#### What problem are you trying to solve?

Being able to look at Hapi's documentation in a dark room without having your eyes blinded.

#### Do you have a new or modified API suggestion to solve the problem?

add a dark mode switch toggle ?

**Comment by lloydbenson** [comment]
hey thanks for this! I am currently working on some bigger issues with the site but I do really appreciate the contribution and I hope to get to it soon. We are in the process of taking over this repository since the change in leadership and I have been working on understanding how things work and implementing some bigger changes. Just wanted to mention this as you aren't being ignored and we hope to get to this soon!

**Comment by lloydbenson** [comment]
@Nargonath is already helping here sorry! So I will let him take it from here while I work on the other items.

**Comment by Nargonath** [comment]
Damn I put the wrong issue ID in the `Fixes #` in the PR commit. 😅 

Thanks @damusix for the work on this. Well done.
