### ISSUE TITLE
joi has been replaced by @hapi/validate

### ISSUE THREAD

**Issue by anlexN** [hapijs/hapi.dev#385]
#### Context

* *node version*:  lts
* *module version*:  all

#### What are you trying to achieve or the steps to reproduce ?
please update docs, when to update?

**Comment by Marsup** [comment]
Validate is for internal use only, you can (and probably should) still use joi for validation purposes.

**Comment by Nargonath** [comment]
I think there is a bit of a misunderstanding here. The only use case where `joi` has been replaced by `@hapi/validate` is for internal use inside `hapi`'s core modules (validation of `hapi`'s API). The reason behind is as Eran took `joi` with him when leaving the organization, we forked the repository to keep `hapi`'s no external dependencies rule. This does not affect `hapi`'s users though and you can continue to provide `joi` schemas to `route.options.validate`. There is no point for you to refer to `@hapi/validate` documentation because you should not use it directly and keep using `joi` instead.

I'll close the issue for now but feel free to comment if I misunderstood your issue in the first place.
