### ISSUE TITLE
Only v20.x API docs visible

### ISSUE THREAD

**Issue by watson** [hapijs/hapi.dev#398]
It seems that all the old versions of the API docs has disappeared from the website. E.g. https://hapi.dev/api/?v=18.4.1 now redirects to https://hapi.dev/api/?v=20.0.0

From the version dropdown menu, only `20.0.0` is available:

![image](https://user-images.githubusercontent.com/10602/92386562-4f484e00-f114-11ea-8889-00c0b76b2bcd.png)

**Comment by Nargonath** [comment]
The versions pre v20 are managed by Eran and not by the TSC hence my guess is that we removed them from the website since we don't have a hold on them and they're also deprecated. You can still find the documentation you are looking for by looking into GitHub since the website is only pulling the data from each API.md repo. For hapi look here: https://github.com/hapijs/hapi/blob/master/API.md

**Comment by AdriVanHoudt** [comment]
Could we still host them with a disclaimer at the top? Or add a disclaimer when going directly to those other versions?

**Comment by devinivy** [comment]
I am in favor of including more versions, and correct me if I'm wrong @hueniverse but it sounds like you have no qualms with that, even for versions that are still receiving updates only via your commercial license.

**Comment by hueniverse** [comment]
People are using old versions. No reason not to provide accessible documentation for those. I think v16 is the oldest reasonable to support. Just the latest version of each open source distribution seems logical.
